import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import { Toaster } from "sonner";
import { ReactLenis } from "@/utils/lenis";
import { AuthProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const DMsans = DM_Sans({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-dmsans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${DMsans.variable} antialiased`}
        >
          <Toaster />
          <AuthProvider>
            <Provider>{children}</Provider>
          </AuthProvider>
        </body>
      </ReactLenis>
    </html>
  );
}
